version: "3"
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - ".docker-volumes/mongo/data:/data/db"
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    env_file:
      - .env
  lego-redis:
    image: redis
    container_name: lego-redis
    ports:
      - 6379:6379
    env_file:
      - .env
    command: >
      -- requirepass ${REDIS_PASSWORD}
  lego-backend:
    image: registry.cn-shanghai.aliyuncs.com/almostlover/lego:1.0.3
    container_name: lego-backend
    ports:
      - 7001:7001
    env_file:
      - .env
