version: '3'
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    env_file:
      - .env
  lego-redis:
    image: redis
    container_name: lego-redis
    ports:
      - 6379:6379
    env_file:
      - .env
    command: >
      -- requirepass ${REDIS_PASSWORD}
  lego-backend:
    depends_on:
      - lego-mongo
      - lego-redis
    build:
      context: . # 当前目录
      dockerfile: Dockerfile # 基于 Dockerfile 构建
    image: lego-backend
    container_name: lego-backend
    ports:
      - 7001:7001
    env_file:
      - .env
