name: test secret and ssh actions
on: [push]

jobs:
  SECRET-SSH-ACTIONS:
    run-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            pwd
            ls -l
            touch secret.txt
            echo ${{ secrets.MY_SECRET }} >> secret.txt
