name: Deploy app to server
on:
  push:
    tags:
      - v*.*.*
jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 测试 github context
      - name: Test github context info
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.sha }}
      # 测试查找并替换
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '{{tag}}'
          replace: ${{ github.ref_name }}
          include: 'docker-compose-online.yml'
      - run: cat docker-compose-online.yml
